version: "3.8"

services:
  app:
    build: .
    container_name: spring-boot-reactive-mongo-ex
    depends_on:
      - mongo
    environment:
      - MONGO_PORT
      - MONGO_URI
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - GRIDFS_BUCKET_NAME
      - MAX_REQUEST_SIZE
      - MAX_FILE_SIZE
      - FILE-SIZE-THRESHOLD
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_PORT: $MONGO_PORT
      ME_CONFIG_MONGODB_AUTH_USERNAME: $DB_USER
      ME_CONFIG_MONGODB_AUTH_PASSWORD: $DB_PASSWORD
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_PASSWORD
      ME_CONFIG_BASICAUTH_USERNAME: $ME_AUTH_USERNAME
      ME_CONFIG_BASICAUTH_PASSWORD: $ME_AUTH_PASSWORD
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
